# Generated by Django 3.0.2 on 2020-01-17 16:11

from django.db import migrations
from datetime import date, timedelta


class Migration(migrations.Migration):

    def create_dates(apps, schema_editor):
        db_alias = schema_editor.connection.alias
        Date = apps.get_model("coosto_lunch", "Date")
        Date.objects.using(db_alias).create(date=date.today())
        for day in range(1825):
            Date.objects.using(db_alias).create(date=date.today() + timedelta(days=day))

    dependencies = [
        ('coosto_lunch', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_dates)
    ]
