# Generated by Django 3.0 on 2019-12-13 13:27

from django.db import migrations


def create_roles(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Role = apps.get_model("coosto_lunch", "Role")
    Role.objects.using(db_alias).create(role="USER")
    Role.objects.using(db_alias).create(role="ADMIN")


class Migration(migrations.Migration):
    dependencies = [
        ('coosto_lunch', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_roles)
    ]
