# Generated by Django 3.0.2 on 2020-01-17 16:15

from django.db import migrations
from django.contrib.auth.admin import User


def create_superuser(apps, schema_editor):
    superuser = User()
    superuser.is_active = True
    superuser.is_superuser = True
    superuser.is_staff = True
    superuser.username = 'mrbakov'
    superuser.email = 'martin.bakov@coosto.com'
    superuser.set_password('xazssqaw5')
    superuser.save()


class Migration(migrations.Migration):
    dependencies = [
        ('coosto_lunch', '0002_auto_20200117_1611'),
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]
