# Generated by Django 3.0 on 2019-12-13 13:27

from django.db import migrations

from django.db import migrations
from datetime import date, timedelta


def create_overviews(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Overview = apps.get_model("coosto_lunch", "Overview")
    Overview.objects.using(db_alias).create(date=date.today())
    Overview.objects.using(db_alias).create(date=date.today() + timedelta(days=1))
    Overview.objects.using(db_alias).create(date=date.today() + timedelta(days=2))
    Overview.objects.using(db_alias).create(date=date.today() + timedelta(days=3))
    Overview.objects.using(db_alias).create(date=date.today() + timedelta(days=4))
    Overview.objects.using(db_alias).create(date=date.today() + timedelta(days=5))
    Overview.objects.using(db_alias).create(date=date.today() + timedelta(days=6))


class Migration(migrations.Migration):
    dependencies = [
        ('coosto_lunch', '0002_auto_20191213_1327'),
    ]

    operations = [
        migrations.RunPython(create_overviews)
    ]
