# Generated by Django 3.0.2 on 2020-01-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coosto_lunch', '0003_auto_20200117_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foodwish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.TextField()),
                ('approved', models.BooleanField()),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
